buildscript {
  repositories {
    mavenCentral()
  }
}

apply plugin: 'application'
apply plugin: 'java'
apply plugin: 'eclipse'
apply plugin: 'idea'

mainClassName = "dk.lb.micro.gradletest.GradleApp"

jar {
  baseName = 'gradletest'
  version = '0.1.0'
  manifest {
    attributes(
            'Main-Class': mainClassName
    )
  }
}


run {
  args System.getProperty("exec.args", "").split()
}
repositories {
  mavenCentral()
}

sourceCompatibility = 1.8
targetCompatibility = 1.8

dependencies {
  testCompile("junit:junit")
}

task wrapper(type: Wrapper) {
  gradleVersion = '4.4'
}